var sampleData = [
    {
        "conversions": "NULL", 
        "imp_rch_ident": "10075", 
        "advertiser_name": "North America", 
        "top_site_imp": "13136", 
        "budget_end_date": "2015-07-01", 
        "budget_max_spend": "153322", 
        "insertion_order_id": "1629644", 
        "impressions": "13494", 
        "top_cntry_imp": "13407", 
        "top_site_name": "partnerselectsite56.com", 
        "viewable_imp": "NULL", 
        "network": "NA", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "United States", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-21", 
        "insertion_order_name": "US_Content Marketing_ST_GPS Private Auction Video_Q2", 
        "clicks": "404", 
        "budget_start_date": "2015-04-01", 
        "total_exposure_mins": "NULL", 
        "total_spend": "243", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "13494", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "NULL", 
        "top_site_id": "22003108", 
        "nflx_campaign_desc": "NULL", 
        "top_country_code": "US  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "1409", 
        "advertiser_name": "DACH", 
        "top_site_imp": "790", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "1230", 
        "insertion_order_id": "1641709", 
        "impressions": "3098", 
        "top_cntry_imp": "3098", 
        "top_site_name": "Rummy LITE - iOS (439873759)", 
        "viewable_imp": "1038", 
        "network": "EU", 
        "measurable_imp": "1707", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Switzerland", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "526", 
        "event_date": "2015-04-25", 
        "insertion_order_name": "CHFR - DareDevil - Banners - Open Exchange - Tablet and Smartphone", 
        "clicks": "14", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "1157", 
        "total_spend": "7", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "3095", 
        "creative_type": "Display", 
        "unmeasurable_imp": "79", 
        "part_viewable_imp": "143", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "423428", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "CH  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "98086", 
        "advertiser_name": "North America", 
        "top_site_imp": "26712", 
        "budget_end_date": "2015-05-01", 
        "budget_max_spend": "10000", 
        "insertion_order_id": "1629332", 
        "impressions": "113853", 
        "top_cntry_imp": "113850", 
        "top_site_name": "ebay.com", 
        "viewable_imp": "141", 
        "network": "NA", 
        "measurable_imp": "178", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "United States", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "26", 
        "event_date": "2015-04-18", 
        "insertion_order_name": "US_Content Marketing_BB_Display_Q2_A/A Test_50/50", 
        "clicks": "82", 
        "budget_start_date": "2015-04-01", 
        "total_exposure_mins": "7374", 
        "total_spend": "633", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "113853", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "11", 
        "nflx_subcampaign_desc": "Content Marketing", 
        "top_site_id": "10017", 
        "nflx_campaign_desc": "Content Marketing", 
        "top_country_code": "US  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "11598", 
        "advertiser_name": "DACH", 
        "top_site_imp": "238402", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "71525", 
        "insertion_order_id": "1640846", 
        "impressions": "727642", 
        "top_cntry_imp": "727613", 
        "top_site_name": "axelspringer-mediapilot.de", 
        "viewable_imp": "150460", 
        "network": "EU", 
        "measurable_imp": "296806", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Germany", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "85144", 
        "event_date": "2015-04-22", 
        "insertion_order_name": "DE - DareDevil - Open Exchange - Banners - Desktop", 
        "clicks": "403", 
        "budget_start_date": "2015-04-11", 
        "total_exposure_mins": "419827", 
        "total_spend": "2830", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "17860", 
        "creative_type": "Display", 
        "unmeasurable_imp": "258", 
        "part_viewable_imp": "61202", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "3354392", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DE  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "50977", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "65992", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "38430", 
        "insertion_order_id": "1639490", 
        "impressions": "67537", 
        "top_cntry_imp": "61903", 
        "top_site_name": "schibstedssp.se", 
        "viewable_imp": "16317", 
        "network": "EU", 
        "measurable_imp": "48178", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Sweden", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "27429", 
        "event_date": "2015-04-22", 
        "insertion_order_name": "SE - Daredevil - Display - PMP", 
        "clicks": "82", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "34421", 
        "total_spend": "752", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "67537", 
        "creative_type": "Display", 
        "unmeasurable_imp": "429", 
        "part_viewable_imp": "4432", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "17932455", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "SE  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "11113", 
        "advertiser_name": "North America", 
        "top_site_imp": "6102", 
        "budget_end_date": "2015-07-01", 
        "budget_max_spend": "49500", 
        "insertion_order_id": "1629947", 
        "impressions": "25034", 
        "top_cntry_imp": "25033", 
        "top_site_name": "youtube.com", 
        "viewable_imp": "8135", 
        "network": "NA", 
        "measurable_imp": "11857", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Canada", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "2324", 
        "event_date": "2015-04-24", 
        "insertion_order_name": "CA_Content Marketing_BB_Display_Q2", 
        "clicks": "17", 
        "budget_start_date": "2015-04-01", 
        "total_exposure_mins": "18773", 
        "total_spend": "118", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "25034", 
        "creative_type": "Display", 
        "unmeasurable_imp": "2", 
        "part_viewable_imp": "1398", 
        "nflx_subcampaign_desc": "Content Marketing", 
        "top_site_id": "11598", 
        "nflx_campaign_desc": "Content Marketing", 
        "top_country_code": "CA  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "53349", 
        "advertiser_name": "UKIE", 
        "top_site_imp": "17659", 
        "budget_end_date": "2015-06-30", 
        "budget_max_spend": "53200", 
        "insertion_order_id": "1655723", 
        "impressions": "93898", 
        "top_cntry_imp": "93502", 
        "top_site_name": "theguardian.com", 
        "viewable_imp": "NULL", 
        "network": "EU", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "United Kingdom", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-24", 
        "insertion_order_name": "UK - Q2 Broad Content - Video", 
        "clicks": "992", 
        "budget_start_date": "2015-04-23", 
        "total_exposure_mins": "NULL", 
        "total_spend": "886", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "88812", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Originals Slate", 
        "top_site_id": "797239", 
        "nflx_campaign_desc": "Content Marketing", 
        "top_country_code": "GB  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "37245", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "54235", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "10675", 
        "insertion_order_id": "1639482", 
        "impressions": "119558", 
        "top_cntry_imp": "119548", 
        "top_site_name": "msn.com/da-dk", 
        "viewable_imp": "20929", 
        "network": "EU", 
        "measurable_imp": "84582", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Denmark", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "38830", 
        "event_date": "2015-04-24", 
        "insertion_order_name": "DK - Daredevil - Display", 
        "clicks": "136", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "71366", 
        "total_spend": "568", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "62129", 
        "creative_type": "Display", 
        "unmeasurable_imp": "134", 
        "part_viewable_imp": "24823", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "8524135", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DK  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "5", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "3", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "13878", 
        "insertion_order_id": "1639483", 
        "impressions": "9", 
        "top_cntry_imp": "9", 
        "top_site_name": "notalwaysright.com", 
        "viewable_imp": "NULL", 
        "network": "EU", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Denmark", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-24", 
        "insertion_order_name": "DK - Daredevil - Video", 
        "clicks": "0", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "NULL", 
        "total_spend": "0", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "9", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "105234", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DK  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "6", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "2", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "13878", 
        "insertion_order_id": "1639483", 
        "impressions": "8", 
        "top_cntry_imp": "8", 
        "top_site_name": "celebs.dailymotion.com", 
        "viewable_imp": "NULL", 
        "network": "EU", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Denmark", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-26", 
        "insertion_order_name": "DK - Daredevil - Video", 
        "clicks": "0", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "NULL", 
        "total_spend": "0", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "8", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "7239718", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DK  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "11335", 
        "advertiser_name": "North America", 
        "top_site_imp": "3817", 
        "budget_end_date": "2015-07-01", 
        "budget_max_spend": "49500", 
        "insertion_order_id": "1629947", 
        "impressions": "24226", 
        "top_cntry_imp": "24223", 
        "top_site_name": "mail.yahoo.com", 
        "viewable_imp": "8424", 
        "network": "NA", 
        "measurable_imp": "12454", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Canada", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "2479", 
        "event_date": "2015-04-23", 
        "insertion_order_name": "CA_Content Marketing_BB_Display_Q2", 
        "clicks": "23", 
        "budget_start_date": "2015-04-01", 
        "total_exposure_mins": "20080", 
        "total_spend": "117", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "24226", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "1551", 
        "nflx_subcampaign_desc": "Content Marketing", 
        "top_site_id": "3099100", 
        "nflx_campaign_desc": "Content Marketing", 
        "top_country_code": "CA  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "16051", 
        "advertiser_name": "DACH", 
        "top_site_imp": "9879", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "20100", 
        "insertion_order_id": "1640850", 
        "impressions": "23673", 
        "top_cntry_imp": "23670", 
        "top_site_name": "gamestar.de", 
        "viewable_imp": "5286", 
        "network": "EU", 
        "measurable_imp": "13680", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Germany", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "3418", 
        "event_date": "2015-04-25", 
        "insertion_order_name": "DE - DareDevil - Banners - PMPs", 
        "clicks": "16", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "10744", 
        "total_spend": "338", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "23673", 
        "creative_type": "Display", 
        "unmeasurable_imp": "15", 
        "part_viewable_imp": "4976", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "19462", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DE  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "16401", 
        "advertiser_name": "France", 
        "top_site_imp": "9167", 
        "budget_end_date": "2015-04-30", 
        "budget_max_spend": "2000", 
        "insertion_order_id": "1640843", 
        "impressions": "34774", 
        "top_cntry_imp": "34766", 
        "top_site_name": "fr.msn.com", 
        "viewable_imp": "1437", 
        "network": "EU", 
        "measurable_imp": "5728", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "France", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "3636", 
        "event_date": "2015-04-25", 
        "insertion_order_name": "DareDevil - Banners - Open Exchange - Tablet and Smartphone", 
        "clicks": "74", 
        "budget_start_date": "2015-04-11", 
        "total_exposure_mins": "3240", 
        "total_spend": "114", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "34774", 
        "creative_type": "Display", 
        "unmeasurable_imp": "9247", 
        "part_viewable_imp": "655", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "190661", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "FR  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "102601", 
        "advertiser_name": "Benelux", 
        "top_site_imp": "29705", 
        "budget_end_date": "2015-05-06", 
        "budget_max_spend": "35000", 
        "insertion_order_id": "1640854", 
        "impressions": "157393", 
        "top_cntry_imp": "157377", 
        "top_site_name": "msn.com/nl-nl/entertainment", 
        "viewable_imp": "56774", 
        "network": "EU", 
        "measurable_imp": "121754", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Netherlands", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "41882", 
        "event_date": "2015-04-25", 
        "insertion_order_name": "NL - DareDevil - PMPs - Banners", 
        "clicks": "282", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "75834", 
        "total_spend": "1316", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "157393", 
        "creative_type": "Display", 
        "unmeasurable_imp": "1274", 
        "part_viewable_imp": "23098", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "8524065", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "NL  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "91135", 
        "advertiser_name": "North America", 
        "top_site_imp": "82811", 
        "budget_end_date": "2015-05-11", 
        "budget_max_spend": "50000", 
        "insertion_order_id": "1631143", 
        "impressions": "322686", 
        "top_cntry_imp": "322601", 
        "top_site_name": "slate.com", 
        "viewable_imp": "292", 
        "network": "NA", 
        "measurable_imp": "741", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "United States", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "289", 
        "event_date": "2015-04-18", 
        "insertion_order_name": "US_Daredevil_Display_PMPs", 
        "clicks": "366", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "19353", 
        "total_spend": "2738", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "322686", 
        "creative_type": "Display", 
        "unmeasurable_imp": "1", 
        "part_viewable_imp": "160", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "10416", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "US  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "53855", 
        "advertiser_name": "North America", 
        "top_site_imp": "24523", 
        "budget_end_date": "2015-07-01", 
        "budget_max_spend": "191652", 
        "insertion_order_id": "1624069", 
        "impressions": "89312", 
        "top_cntry_imp": "89312", 
        "top_site_name": "yahoo.com", 
        "viewable_imp": "8224", 
        "network": "NA", 
        "measurable_imp": "12253", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "United States", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "2517", 
        "event_date": "2015-04-27", 
        "insertion_order_name": "US_Content Marketing_LP_Display_Q2", 
        "clicks": "0", 
        "budget_start_date": "2015-04-01", 
        "total_exposure_mins": "7913", 
        "total_spend": "475", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "89312", 
        "creative_type": "Display", 
        "unmeasurable_imp": "1", 
        "part_viewable_imp": "1512", 
        "nflx_subcampaign_desc": "Content Marketing", 
        "top_site_id": "166816", 
        "nflx_campaign_desc": "Content Marketing", 
        "top_country_code": "US  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "6726", 
        "advertiser_name": "DACH", 
        "top_site_imp": "3007", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "1100", 
        "insertion_order_id": "1641651", 
        "impressions": "11176", 
        "top_cntry_imp": "11175", 
        "top_site_name": "funcloud.com", 
        "viewable_imp": "4", 
        "network": "EU", 
        "measurable_imp": "4", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Austria", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "0", 
        "event_date": "2015-04-18", 
        "insertion_order_name": "AT - DareDevil - Banners - Open Exchange - Tablet and Smartphone", 
        "clicks": "16", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "0", 
        "total_spend": "27", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "11171", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "0", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "531058", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "AT  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "343535", 
        "advertiser_name": "France", 
        "top_site_imp": "128288", 
        "budget_end_date": "2015-04-30", 
        "budget_max_spend": "145000", 
        "insertion_order_id": "1639444", 
        "impressions": "542847", 
        "top_cntry_imp": "542779", 
        "top_site_name": "01-edito-atf-laplacemedia-3.fr", 
        "viewable_imp": "206", 
        "network": "EU", 
        "measurable_imp": "918", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "France", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "199", 
        "event_date": "2015-04-19", 
        "insertion_order_name": "DareDevil  - PMP - Banners", 
        "clicks": "678", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "73112", 
        "total_spend": "9240", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "542847", 
        "creative_type": "Display", 
        "unmeasurable_imp": "2", 
        "part_viewable_imp": "513", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "2665997", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "FR  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "848", 
        "advertiser_name": "Benelux", 
        "top_site_imp": "750", 
        "budget_end_date": "2015-05-06", 
        "budget_max_spend": "700", 
        "insertion_order_id": "1641645", 
        "impressions": "1313", 
        "top_cntry_imp": "1298", 
        "top_site_name": "hln.be", 
        "viewable_imp": "NULL", 
        "network": "EU", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Belgium", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-22", 
        "insertion_order_name": "BEFL - DareDevil - Open Exchange - Video - Tablet Smartphone", 
        "clicks": "112", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "NULL", 
        "total_spend": "23", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "943", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "91833", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "BE  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "0", 
        "advertiser_name": "Brazil", 
        "top_site_imp": "1338208", 
        "budget_end_date": "2015-05-25", 
        "budget_max_spend": "400000", 
        "insertion_order_id": "1636974", 
        "impressions": "6044571", 
        "top_cntry_imp": "6060013", 
        "top_site_name": "uol.com.br", 
        "viewable_imp": "NULL", 
        "network": "LATAM", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Brazil", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-24", 
        "insertion_order_name": "Apr2015_BR_Originals_Daredevil", 
        "clicks": "18345", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "NULL", 
        "total_spend": "17083", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "0", 
        "creative_type": "Display", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "63190", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "BR  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "17852", 
        "advertiser_name": "Mexico - Netflix", 
        "top_site_imp": "252748", 
        "budget_end_date": "2015-05-16", 
        "budget_max_spend": "70000", 
        "insertion_order_id": "1640540", 
        "impressions": "41280", 
        "top_cntry_imp": "705071", 
        "top_site_name": "proceso.com.mx", 
        "viewable_imp": "NULL", 
        "network": "LATAM", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Mexico", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-26", 
        "insertion_order_name": "Apr2015_MX_Originals_Daredevil", 
        "clicks": "5977", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "NULL", 
        "total_spend": "321", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "41280", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "31254", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "MX  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "1081", 
        "advertiser_name": "DACH", 
        "top_site_imp": "375", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "1845", 
        "insertion_order_id": "1641706", 
        "impressions": "2048", 
        "top_cntry_imp": "2047", 
        "top_site_name": "cineman.ch", 
        "viewable_imp": "254", 
        "network": "EU", 
        "measurable_imp": "878", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Switzerland", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "504", 
        "event_date": "2015-04-20", 
        "insertion_order_name": "CHDE - DareDevil - Banners - Open Exchange - Tablet and Smartphone", 
        "clicks": "6", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "47", 
        "total_spend": "11", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "2044", 
        "creative_type": "Display", 
        "unmeasurable_imp": "152", 
        "part_viewable_imp": "120", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "394327", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "CH  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "1007", 
        "advertiser_name": "Benelux", 
        "top_site_imp": "649", 
        "budget_end_date": "2015-05-06", 
        "budget_max_spend": "1000", 
        "insertion_order_id": "1641643", 
        "impressions": "1646", 
        "top_cntry_imp": "1646", 
        "top_site_name": "quefaire.be", 
        "viewable_imp": "5", 
        "network": "EU", 
        "measurable_imp": "8", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Belgium", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "2", 
        "event_date": "2015-04-19", 
        "insertion_order_name": "BEFR - DareDevil - Open Exchange - Banners - Tablet Smartphone", 
        "clicks": "6", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "6", 
        "total_spend": "7", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "1646", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "1", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "37610", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "BE  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "35775", 
        "advertiser_name": "Australia & New Zealand", 
        "top_site_imp": "21554", 
        "budget_end_date": "2015-07-01", 
        "budget_max_spend": "97524", 
        "insertion_order_id": "1612929", 
        "impressions": "64443", 
        "top_cntry_imp": "64422", 
        "top_site_name": "cbsinteractive.com", 
        "viewable_imp": "10834", 
        "network": "NA", 
        "measurable_imp": "28832", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Australia", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "14787", 
        "event_date": "2015-04-20", 
        "insertion_order_name": "AU_Content Marketing_CE_Display_Q2", 
        "clicks": "200", 
        "budget_start_date": "2015-03-23", 
        "total_exposure_mins": "15110", 
        "total_spend": "555", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "55563", 
        "creative_type": "Display", 
        "unmeasurable_imp": "8638", 
        "part_viewable_imp": "3211", 
        "nflx_subcampaign_desc": "Bloodline", 
        "top_site_id": "20336", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "AU  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "10796", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "12776", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "10675", 
        "insertion_order_id": "1639482", 
        "impressions": "113140", 
        "top_cntry_imp": "113129", 
        "top_site_name": "031455c8b2a946c6.anonymous.google", 
        "viewable_imp": "49", 
        "network": "EU", 
        "measurable_imp": "169", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Denmark", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "78", 
        "event_date": "2015-04-18", 
        "insertion_order_name": "DK - Daredevil - Display", 
        "clicks": "130", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "4053", 
        "total_spend": "364", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "25132", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "42", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "76433", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DK  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "118027", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "186365", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "26688", 
        "insertion_order_id": "1639481", 
        "impressions": "187932", 
        "top_cntry_imp": "187899", 
        "top_site_name": "danskudgivernetvaerk.dk", 
        "viewable_imp": "137949", 
        "network": "EU", 
        "measurable_imp": "166341", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Denmark", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "20248", 
        "event_date": "2015-04-22", 
        "insertion_order_name": "DK - Daredevil - Display - PMP", 
        "clicks": "165", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "91438", 
        "total_spend": "968", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "187932", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "8144", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "695041", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "DK  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "5405", 
        "advertiser_name": "DACH", 
        "top_site_imp": "2755", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "5600", 
        "insertion_order_id": "1641655", 
        "impressions": "8501", 
        "top_cntry_imp": "8500", 
        "top_site_name": "prosieben.ch", 
        "viewable_imp": "2649", 
        "network": "EU", 
        "measurable_imp": "6230", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Switzerland", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "727", 
        "event_date": "2015-04-26", 
        "insertion_order_name": "CHDE - DareDevil - PMP - Banners", 
        "clicks": "22", 
        "budget_start_date": "2015-04-13", 
        "total_exposure_mins": "14988", 
        "total_spend": "129", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "8133", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "2854", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "443912", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "CH  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "7", 
        "advertiser_name": "Nordics", 
        "top_site_imp": "13492", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "8540", 
        "insertion_order_id": "1642634", 
        "impressions": "26183", 
        "top_cntry_imp": "26181", 
        "top_site_name": "tv2.no", 
        "viewable_imp": "88", 
        "network": "EU", 
        "measurable_imp": "206", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Norway", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "50", 
        "event_date": "2015-04-19", 
        "insertion_order_name": "NO - Daredevil - Display", 
        "clicks": "32", 
        "budget_start_date": "2015-04-10", 
        "total_exposure_mins": "2431", 
        "total_spend": "99", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "8", 
        "creative_type": "Display", 
        "unmeasurable_imp": "0", 
        "part_viewable_imp": "68", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "37210", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "NO  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "2270", 
        "advertiser_name": "North America", 
        "top_site_imp": "1461", 
        "budget_end_date": "2015-05-04", 
        "budget_max_spend": "2324", 
        "insertion_order_id": "1635560", 
        "impressions": "7702", 
        "top_cntry_imp": "7698", 
        "top_site_name": "pandora.com", 
        "viewable_imp": "NULL", 
        "network": "NA", 
        "measurable_imp": "NULL", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "United States", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "NULL", 
        "event_date": "2015-04-23", 
        "insertion_order_name": "US_Content Marketing_Media Mix_Video_Q2_SPO", 
        "clicks": "23", 
        "budget_start_date": "2015-04-07", 
        "total_exposure_mins": "NULL", 
        "total_spend": "58", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "7702", 
        "creative_type": "Video", 
        "unmeasurable_imp": "NULL", 
        "part_viewable_imp": "NULL", 
        "nflx_subcampaign_desc": "Content Marketing", 
        "top_site_id": "17326", 
        "nflx_campaign_desc": "Content Marketing", 
        "top_country_code": "US  "
    }, 
    {
        "conversions": "NULL", 
        "imp_rch_ident": "4088", 
        "advertiser_name": "DACH", 
        "top_site_imp": "1089", 
        "budget_end_date": "2015-05-10", 
        "budget_max_spend": "1845", 
        "insertion_order_id": "1641706", 
        "impressions": "8225", 
        "top_cntry_imp": "8219", 
        "top_site_name": "eBay Kleinanzeigen - Kostenlos. Einfach. Lokal. - iOS (382596778)", 
        "viewable_imp": "1306", 
        "network": "EU", 
        "measurable_imp": "3519", 
        "overall_budget_max_impressions": "NULL", 
        "top_country_desc": "Switzerland", 
        "ltv_m60": "NULL", 
        "unviewable_imp": "1977", 
        "event_date": "2015-04-25", 
        "insertion_order_name": "CHDE - DareDevil - Banners - Open Exchange - Tablet and Smartphone", 
        "clicks": "35", 
        "budget_start_date": "2015-04-12", 
        "total_exposure_mins": "420", 
        "total_spend": "32", 
        "load_ts": "2015-04-28 13:29:59.0+00:00", 
        "imp_ident": "8207", 
        "creative_type": "Display", 
        "unmeasurable_imp": "299", 
        "part_viewable_imp": "236", 
        "nflx_subcampaign_desc": "Daredevil", 
        "top_site_id": "19969756", 
        "nflx_campaign_desc": "Originals", 
        "top_country_code": "CH  "
    }
]
